# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(max_length=126)),
                ('date_taken', models.DateField(default=datetime.datetime(2017, 9, 13, 18, 19, 40, 106598, tzinfo=utc))),
                ('date_uploaded', models.DateField(default=datetime.datetime(2017, 9, 13, 18, 19, 40, 106645, tzinfo=utc))),
                ('image_data', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('contact_email', models.EmailField(max_length=254)),
                ('photo_watermark', models.ImageField(upload_to='./')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=126, unique=True)),
                ('associated_images', models.ManyToManyField(related_name='tags', to='photography.Photograph')),
            ],
        ),
        migrations.AddField(
            model_name='photograph',
            name='image_photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='associated_photographs', to='photography.Photographer'),
        ),
    ]
