# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='alt_text',
            field=models.CharField(blank=True, max_length=126),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2017, 9, 13, 20, 9, 45, 757803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2017, 9, 13, 20, 9, 45, 757849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='photo_watermark',
            field=models.ImageField(blank=True, upload_to='./'),
        ),
    ]
