# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photography', '0004_auto_20171004_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photograph',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 14, 12, 25, 261218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 14, 12, 25, 261268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='image_photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associated_photographs', to='photography.Photographer'),
        ),
    ]
